Repository maidsafe/safe_browser, pull requests merged in 2018-08, with the labels that each got.

#286 Resolves #298 chore/ui: on did-fail-load, properly error and render fail message in UI
  CHANGELOG.md
  __e2e__/peruse.spec.js
  __tests__/utils/urlHelpers.spec.js
  app/components/Tab/Tab.jsx
Labels: bug, to review

#301 fix/safe-protocol: peruse was defaulting urls with no subdomain to www.<hostname>
  app/extensions/safe/protocols/safe.js
Labels: bug

#302 e2e tests for backward/forward
  __e2e__/peruse.spec.js
  app/components/AddressBar/ButtonsLHS/ButtonsLHS.jsx
Labels: enhancement

#305 minor update in readme
  README.md
Labels: enhancement

#303 Resolves #293 fix/auth: mock-dev on Windows now able to auth on login
  CHANGELOG.md
  app/background.manageRemoteCalls.js
  app/background.process.development.js
  app/constants.js
  app/extensions/index.js
  app/extensions/safe/actions/authenticator_actions.js
  app/extensions/safe/auth-web-app/index.js
  app/extensions/safe/ffi/ipc.js
  app/extensions/safe/index.js
  app/extensions/safe/manageAuthNotifications.js
  app/extensions/safe/network/authenticator-comms.js
  app/extensions/safe/peruseSafeApp/index.js
  app/logger.js
  app/main.development.js
  app/package.json
  package.json
  yarn.lock
Labels: to review
