Repository maidsafe/safe_browser, pull requests merged in 2018-12, with the labels that each got.

#445 fix(package): crust.config matches executable on Windows
  post-pack.js
Labels: to review

#446 Enhance back/forwards
  __tests__/components/AddressBar.spec.js
  __tests__/components/Browser.spec.js
  __tests__/reducers/tabs.spec.js
  app/components/AddressBar/AddressBar.jsx
  app/components/AddressBar/ButtonsLHS/ButtonsLHS.jsx
  app/extensions/safe/actions/authenticator_actions.js
  app/reducers/tabs.js
Labels: to review

#448 fix(UI): when the app name is just - or _ characters render them in the authenticator as they are
  app/extensions/safe/auth-web-app/utils.js
Labels: RC-2, bug

#488 doc(Readme): Add more details about the experimental APIs/features exposed
  README.md
  resources/readme/experiments-toggle.png
  resources/readme/experiments-visual-indicator.png
  resources/readme/md-viewer.png
  resources/readme/mock-visual-indicator.png
  resources/readme/webid-selector.png
  resources/readme/xorurl-screenshot.png
Labels: enhancement

#458 test(settingsMenu): add e2e tests for settings menu
  __e2e__/peruse.spec.js
  app/components/AddressBar/AddressBar.jsx
  app/components/CustomMenu/CustomMenu.jsx
  app/constants.js
  app/extensions/safe/components/wrapAddressBarButtonsRHS.js
Labels: to review
