Repository maidsafe/safe_browser, pull requests merged in 2019-03, with the labels that each got.

#624 fix(Chromium): Update electron to 2.0.18
  package.json
  yarn.lock
Labels: 0.11.3, enhancement

#637 chore(build): bundle package with libgconf-2.so.4
  package.json
  post-pack.js
  resources/libgconf-2.so.4
Labels: to review

#649 chore(lint): Remove tslint as overkill
  .eslintrc.js
  package.json
  yarn.lock
Labels: 0.11.3
